from __future__ import annotations

from pathlib import Path
from typing import Any

from drlf.ingestion.part_b_common import (
    PartBLoadSpec,
    decimal,
    integer,
    load_part_b_pages,
    required_decimal,
    required_integer,
    required_text,
    text,
)
from drlf.sources.part_b_provider_manifest import (
    AGGREGATION_KEYS,
    DATASET_SLUG,
    DATASET_TYPE_UUID,
)

PROVIDER_COLUMNS = (
    "source_release_id",
    "data_year",
    "rendering_npi",
    "provider_last_org_name",
    "provider_first_name",
    "provider_middle_initial",
    "provider_credentials",
    "entity_code",
    "provider_address_line1",
    "provider_address_line2",
    "provider_city",
    "provider_state",
    "provider_state_fips",
    "provider_zip5",
    "provider_ruca",
    "provider_ruca_description",
    "provider_country",
    "provider_type",
    "medicare_participation_indicator",
    "total_hcpcs_codes",
    "total_beneficiaries",
    "total_services",
    "total_submitted_charge",
    "total_medicare_allowed_amount",
    "total_medicare_payment_amount",
    "total_medicare_standardized_amount",
    "drug_suppression_indicator",
    "drug_total_hcpcs_codes",
    "drug_total_beneficiaries",
    "drug_total_services",
    "drug_submitted_charge",
    "drug_medicare_allowed_amount",
    "drug_medicare_payment_amount",
    "drug_medicare_standardized_amount",
    "medical_suppression_indicator",
    "medical_total_hcpcs_codes",
    "medical_total_beneficiaries",
    "medical_total_services",
    "medical_submitted_charge",
    "medical_medicare_allowed_amount",
    "medical_medicare_payment_amount",
    "medical_medicare_standardized_amount",
    "beneficiary_average_age",
    "beneficiary_age_lt_65_count",
    "beneficiary_age_65_74_count",
    "beneficiary_age_75_84_count",
    "beneficiary_age_gt_84_count",
    "beneficiary_female_count",
    "beneficiary_male_count",
    "beneficiary_race_white_count",
    "beneficiary_race_black_count",
    "beneficiary_race_api_count",
    "beneficiary_race_hispanic_count",
    "beneficiary_race_native_indian_count",
    "beneficiary_race_other_count",
    "beneficiary_dual_count",
    "beneficiary_nondual_count",
    "beneficiary_adhd_other_conduct_disorder_percent",
    "beneficiary_alcohol_drug_use_disorder_percent",
    "tobacco_pct",
    "beneficiary_alzheimer_non_alzheimer_dementia_percent",
    "beneficiary_anxiety_disorder_percent",
    "beneficiary_bipolar_disorder_percent",
    "beneficiary_mood_disorder_percent",
    "beneficiary_depression_percent",
    "beneficiary_personality_disorder_percent",
    "beneficiary_ptsd_percent",
    "beneficiary_schizophrenia_other_psychotic_disorder_percent",
    "asthma_pct",
    "beneficiary_atrial_fibrillation_percent",
    "beneficiary_cancer_percent",
    "beneficiary_chronic_kidney_disease_percent",
    "copd_pct",
    "beneficiary_diabetes_percent",
    "beneficiary_heart_failure_non_ischemic_heart_disease_percent",
    "beneficiary_hyperlipidemia_percent",
    "beneficiary_hypertension_percent",
    "beneficiary_ischemic_heart_disease_percent",
    "beneficiary_osteoporosis_percent",
    "beneficiary_parkinson_disease_percent",
    "beneficiary_arthritis_percent",
    "beneficiary_stroke_tia_percent",
    "average_risk_score",
)


def _row_values(
    row: dict[str, Any],
    source_release_id: int,
    data_year: int,
) -> tuple[Any, ...]:
    """Map the complete published provider summary without changing numeric units."""
    return (
        source_release_id,
        data_year,
        required_text(row, "Rndrng_NPI"),
        text(row.get("Rndrng_Prvdr_Last_Org_Name")),
        text(row.get("Rndrng_Prvdr_First_Name")),
        text(row.get("Rndrng_Prvdr_MI")),
        text(row.get("Rndrng_Prvdr_Crdntls")),
        required_text(row, "Rndrng_Prvdr_Ent_Cd"),
        text(row.get("Rndrng_Prvdr_St1")),
        text(row.get("Rndrng_Prvdr_St2")),
        text(row.get("Rndrng_Prvdr_City")),
        text(row.get("Rndrng_Prvdr_State_Abrvtn")),
        text(row.get("Rndrng_Prvdr_State_FIPS")),
        text(row.get("Rndrng_Prvdr_Zip5")),
        text(row.get("Rndrng_Prvdr_RUCA")),
        text(row.get("Rndrng_Prvdr_RUCA_Desc")),
        text(row.get("Rndrng_Prvdr_Cntry")),
        required_text(row, "Rndrng_Prvdr_Type"),
        required_text(row, "Rndrng_Prvdr_Mdcr_Prtcptg_Ind"),
        required_integer(row, "Tot_HCPCS_Cds"),
        required_integer(row, "Tot_Benes"),
        required_decimal(row, "Tot_Srvcs"),
        required_decimal(row, "Tot_Sbmtd_Chrg"),
        required_decimal(row, "Tot_Mdcr_Alowd_Amt"),
        required_decimal(row, "Tot_Mdcr_Pymt_Amt"),
        required_decimal(row, "Tot_Mdcr_Stdzd_Amt"),
        text(row.get("Drug_Sprsn_Ind")),
        integer(row.get("Drug_Tot_HCPCS_Cds")),
        integer(row.get("Drug_Tot_Benes")),
        decimal(row.get("Drug_Tot_Srvcs")),
        decimal(row.get("Drug_Sbmtd_Chrg")),
        decimal(row.get("Drug_Mdcr_Alowd_Amt")),
        decimal(row.get("Drug_Mdcr_Pymt_Amt")),
        decimal(row.get("Drug_Mdcr_Stdzd_Amt")),
        text(row.get("Med_Sprsn_Ind")),
        integer(row.get("Med_Tot_HCPCS_Cds")),
        integer(row.get("Med_Tot_Benes")),
        decimal(row.get("Med_Tot_Srvcs")),
        decimal(row.get("Med_Sbmtd_Chrg")),
        decimal(row.get("Med_Mdcr_Alowd_Amt")),
        decimal(row.get("Med_Mdcr_Pymt_Amt")),
        decimal(row.get("Med_Mdcr_Stdzd_Amt")),
        decimal(row.get("Bene_Avg_Age")),
        integer(row.get("Bene_Age_LT_65_Cnt")),
        integer(row.get("Bene_Age_65_74_Cnt")),
        integer(row.get("Bene_Age_75_84_Cnt")),
        integer(row.get("Bene_Age_GT_84_Cnt")),
        integer(row.get("Bene_Feml_Cnt")),
        integer(row.get("Bene_Male_Cnt")),
        integer(row.get("Bene_Race_Wht_Cnt")),
        integer(row.get("Bene_Race_Black_Cnt")),
        integer(row.get("Bene_Race_API_Cnt")),
        integer(row.get("Bene_Race_Hspnc_Cnt")),
        integer(row.get("Bene_Race_NatInd_Cnt")),
        integer(row.get("Bene_Race_Othr_Cnt")),
        integer(row.get("Bene_Dual_Cnt")),
        integer(row.get("Bene_Ndual_Cnt")),
        decimal(row.get("Bene_CC_BH_ADHD_OthCD_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Alcohol_Drug_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Tobacco_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Alz_NonAlzdem_V2_Pct")),
        decimal(row.get("Bene_CC_BH_Anxiety_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Bipolar_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Mood_V2_Pct")),
        decimal(row.get("Bene_CC_BH_Depress_V1_Pct")),
        decimal(row.get("Bene_CC_BH_PD_V1_Pct")),
        decimal(row.get("Bene_CC_BH_PTSD_V1_Pct")),
        decimal(row.get("Bene_CC_BH_Schizo_OthPsy_V1_Pct")),
        decimal(row.get("Bene_CC_PH_Asthma_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Afib_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Cancer6_V2_Pct")),
        decimal(row.get("Bene_CC_PH_CKD_V2_Pct")),
        decimal(row.get("Bene_CC_PH_COPD_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Diabetes_V2_Pct")),
        decimal(row.get("Bene_CC_PH_HF_NonIHD_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Hyperlipidemia_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Hypertension_V2_Pct")),
        decimal(row.get("Bene_CC_PH_IschemicHeart_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Osteoporosis_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Parkinson_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Arthritis_V2_Pct")),
        decimal(row.get("Bene_CC_PH_Stroke_TIA_V2_Pct")),
        decimal(row.get("Bene_Avg_Risk_Scre")),
    )


_LOAD_SPEC = PartBLoadSpec(
    dataset_label="CMS Medicare Physician & Other Practitioners by Provider",
    dataset_slug=DATASET_SLUG,
    dataset_type_uuid=DATASET_TYPE_UUID,
    aggregation_keys=AGGREGATION_KEYS,
    table_name="part_b_provider",
    columns=PROVIDER_COLUMNS,
    row_mapper=_row_values,
)


def load_part_b_provider(
    database_url: str,
    manifest_path: Path,
    *,
    code_commit: str,
    pipeline_version: str,
    case_id: str | None = None,
) -> tuple[int, int]:
    """Load a complete retained Part B provider-summary API manifest."""
    return load_part_b_pages(
        database_url,
        manifest_path,
        spec=_LOAD_SPEC,
        code_commit=code_commit,
        pipeline_version=pipeline_version,
        case_id=case_id,
    )
